"""track knowledge proposal base version

Revision ID: 10a9e886bfb6
Revises: babb955e0623
Create Date: 2026-10-05 10:13:07.445085
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "10a9e886bfb6"
down_revision: str | None = "babb955e0623"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledge_proposals",
        sa.Column("base_version", sa.String(length=30), nullable=True),
    )
    op.execute(
        sa.text(
            "UPDATE knowledge_proposals "
            "SET base_version = (SELECT version FROM knowledge_packs "
            "WHERE knowledge_packs.id = knowledge_proposals.knowledge_pack_id)"
        )
    )
    with op.batch_alter_table("knowledge_proposals") as batch_op:
        batch_op.alter_column(
            "base_version",
            existing_type=sa.String(length=30),
            nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("knowledge_proposals") as batch_op:
        batch_op.drop_column("base_version")
    # ### end Alembic commands ###
