"""initial schema

Revision ID: 172e2a48bade
Revises:
Create Date: 2026-10-05 09:44:46.864196
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "172e2a48bade"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("domain", sa.String(length=120), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("level", sa.String(length=2), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("free_feasibility", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_domain"), "agents", ["domain"], unique=False)
    op.create_index(op.f("ix_agents_level"), "agents", ["level"], unique=False)
    op.create_index(op.f("ix_agents_name"), "agents", ["name"], unique=False)
    op.create_index(op.f("ix_agents_slug"), "agents", ["slug"], unique=True)
    op.create_index(op.f("ix_agents_status"), "agents", ["status"], unique=False)
    op.create_index(op.f("ix_agents_tier"), "agents", ["tier"], unique=False)
    op.create_table(
        "knowledge_packs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("domain", sa.String(length=120), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=500), nullable=False),
        sa.Column("source_license", sa.String(length=100), nullable=False),
        sa.Column("reliability", sa.Double(), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("last_verified", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_knowledge_packs_domain"), "knowledge_packs", ["domain"], unique=False)
    op.create_index(op.f("ix_knowledge_packs_name"), "knowledge_packs", ["name"], unique=False)
    op.create_index(op.f("ix_knowledge_packs_slug"), "knowledge_packs", ["slug"], unique=True)
    op.create_table(
        "missions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("mission_context", sa.Text(), nullable=False),
        sa.Column("agent_ids", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_missions_status"), "missions", ["status"], unique=False)
    op.create_table(
        "runtime_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("domain", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("prerequisites", sa.JSON(), nullable=False),
        sa.Column("required_tools", sa.JSON(), nullable=False),
        sa.Column("required_level", sa.String(length=2), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skills_domain"), "skills", ["domain"], unique=False)
    op.create_index(op.f("ix_skills_name"), "skills", ["name"], unique=False)
    op.create_index(op.f("ix_skills_slug"), "skills", ["slug"], unique=True)
    op.create_table(
        "tool_registry",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("input_schema", sa.JSON(), nullable=False),
        sa.Column("output_schema", sa.JSON(), nullable=False),
        sa.Column("risk", sa.String(length=20), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("sandbox_compatible", sa.Boolean(), nullable=False),
        sa.Column("rollback_supported", sa.Boolean(), nullable=False),
        sa.Column("dependencies", sa.JSON(), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("license", sa.String(length=100), nullable=False),
        sa.Column("executable", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tool_registry_name"), "tool_registry", ["name"], unique=True)
    op.create_table(
        "activity_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_events_agent_id"), "activity_events", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_events_event_type"), "activity_events", ["event_type"], unique=False
    )
    op.create_table(
        "agent_permissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "tool_name"),
    )
    op.create_index(
        op.f("ix_agent_permissions_agent_id"), "agent_permissions", ["agent_id"], unique=False
    )
    op.create_table(
        "agent_skills",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("skill_id", sa.String(length=36), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "skill_id"),
    )
    op.create_index(op.f("ix_agent_skills_agent_id"), "agent_skills", ["agent_id"], unique=False)
    op.create_index(op.f("ix_agent_skills_skill_id"), "agent_skills", ["skill_id"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_approvals_agent_id"), "approvals", ["agent_id"], unique=False)
    op.create_table(
        "audit_records",
        sa.Column("sequence", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("risk", sa.String(length=20), nullable=False),
        sa.Column("outcome", sa.String(length=30), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=False),
        sa.Column("entry_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("sequence"),
        sa.UniqueConstraint("entry_hash"),
    )
    op.create_index(op.f("ix_audit_records_agent_id"), "audit_records", ["agent_id"], unique=False)
    op.create_table(
        "evaluations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("benchmark_id", sa.String(length=100), nullable=False),
        sa.Column("score", sa.Double(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evaluations_agent_id"), "evaluations", ["agent_id"], unique=False)
    op.create_table(
        "mission_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mission_id", sa.String(length=36), nullable=False),
        sa.Column("previous_status", sa.String(length=30), nullable=True),
        sa.Column("current_status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mission_events_mission_id"), "mission_events", ["mission_id"], unique=False
    )
    op.create_table(
        "certificates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("level", sa.String(length=2), nullable=False),
        sa.Column("evaluation_id", sa.String(length=36), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "level"),
        sa.UniqueConstraint("evaluation_id"),
    )
    op.create_index(op.f("ix_certificates_agent_id"), "certificates", ["agent_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_certificates_agent_id"), table_name="certificates")
    op.drop_table("certificates")
    op.drop_index(op.f("ix_mission_events_mission_id"), table_name="mission_events")
    op.drop_table("mission_events")
    op.drop_index(op.f("ix_evaluations_agent_id"), table_name="evaluations")
    op.drop_table("evaluations")
    op.drop_index(op.f("ix_audit_records_agent_id"), table_name="audit_records")
    op.drop_table("audit_records")
    op.drop_index(op.f("ix_approvals_agent_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_agent_skills_skill_id"), table_name="agent_skills")
    op.drop_index(op.f("ix_agent_skills_agent_id"), table_name="agent_skills")
    op.drop_table("agent_skills")
    op.drop_index(op.f("ix_agent_permissions_agent_id"), table_name="agent_permissions")
    op.drop_table("agent_permissions")
    op.drop_index(op.f("ix_activity_events_event_type"), table_name="activity_events")
    op.drop_index(op.f("ix_activity_events_agent_id"), table_name="activity_events")
    op.drop_table("activity_events")
    op.drop_index(op.f("ix_tool_registry_name"), table_name="tool_registry")
    op.drop_table("tool_registry")
    op.drop_index(op.f("ix_skills_slug"), table_name="skills")
    op.drop_index(op.f("ix_skills_name"), table_name="skills")
    op.drop_index(op.f("ix_skills_domain"), table_name="skills")
    op.drop_table("skills")
    op.drop_table("runtime_settings")
    op.drop_index(op.f("ix_missions_status"), table_name="missions")
    op.drop_table("missions")
    op.drop_index(op.f("ix_knowledge_packs_slug"), table_name="knowledge_packs")
    op.drop_index(op.f("ix_knowledge_packs_name"), table_name="knowledge_packs")
    op.drop_index(op.f("ix_knowledge_packs_domain"), table_name="knowledge_packs")
    op.drop_table("knowledge_packs")
    op.drop_index(op.f("ix_agents_tier"), table_name="agents")
    op.drop_index(op.f("ix_agents_status"), table_name="agents")
    op.drop_index(op.f("ix_agents_slug"), table_name="agents")
    op.drop_index(op.f("ix_agents_name"), table_name="agents")
    op.drop_index(op.f("ix_agents_level"), table_name="agents")
    op.drop_index(op.f("ix_agents_domain"), table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
