"""add system agents

Revision ID: 5ba9b2a8c3c1
Revises: 172e2a48bade
Create Date: 2026-10-05 09:53:59.833696
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5ba9b2a8c3c1'
down_revision: str | None = '172e2a48bade'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('operating_instructions', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_agents_slug'), 'system_agents', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_agents_slug'), table_name='system_agents')
    op.drop_table('system_agents')
    # ### end Alembic commands ###