"""add knowledge review workflow

Revision ID: babb955e0623
Revises: 5ba9b2a8c3c1
Create Date: 2026-10-05 10:03:15.256096
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "babb955e0623"
down_revision: str | None = "5ba9b2a8c3c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_knowledge",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("knowledge_pack_id", sa.String(length=36), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_pack_id"],
            ["knowledge_packs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "knowledge_pack_id"),
    )
    op.create_index(
        op.f("ix_agent_knowledge_agent_id"), "agent_knowledge", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_knowledge_knowledge_pack_id"),
        "agent_knowledge",
        ["knowledge_pack_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_proposals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("knowledge_pack_id", sa.String(length=36), nullable=False),
        sa.Column("proposed_content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=500), nullable=False),
        sa.Column("source_license", sa.String(length=100), nullable=False),
        sa.Column("reliability", sa.Float(), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=False),
        sa.Column("proposed_by", sa.String(length=160), nullable=False),
        sa.Column("minimum_score", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("evaluation_score", sa.Float(), nullable=True),
        sa.Column("evaluation_details", sa.JSON(), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["knowledge_pack_id"],
            ["knowledge_packs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_proposals_knowledge_pack_id"),
        "knowledge_proposals",
        ["knowledge_pack_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_proposals_status"), "knowledge_proposals", ["status"], unique=False
    )
    op.create_table(
        "knowledge_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("knowledge_pack_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=500), nullable=False),
        sa.Column("source_license", sa.String(length=100), nullable=False),
        sa.Column("reliability", sa.Float(), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["knowledge_pack_id"],
            ["knowledge_packs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("knowledge_pack_id", "version"),
    )
    op.create_index(
        op.f("ix_knowledge_revisions_knowledge_pack_id"),
        "knowledge_revisions",
        ["knowledge_pack_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_knowledge_revisions_knowledge_pack_id"), table_name="knowledge_revisions"
    )
    op.drop_table("knowledge_revisions")
    op.drop_index(op.f("ix_knowledge_proposals_status"), table_name="knowledge_proposals")
    op.drop_index(
        op.f("ix_knowledge_proposals_knowledge_pack_id"), table_name="knowledge_proposals"
    )
    op.drop_table("knowledge_proposals")
    op.drop_index(op.f("ix_agent_knowledge_knowledge_pack_id"), table_name="agent_knowledge")
    op.drop_index(op.f("ix_agent_knowledge_agent_id"), table_name="agent_knowledge")
    op.drop_table("agent_knowledge")
    # ### end Alembic commands ###
