"""add workspace change proposals

Revision ID: f607643600e2
Revises: 10a9e886bfb6
Create Date: 2026-10-05 10:20:12.836479
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f607643600e2'
down_revision: Union[str, None] = '10a9e886bfb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=False),
    sa.Column('expected_hash', sa.String(length=64), nullable=False),
    sa.Column('proposed_content', sa.Text(), nullable=False),
    sa.Column('unified_diff', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requester', sa.String(length=160), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_changes_status'), 'workspace_changes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_changes_status'), table_name='workspace_changes')
    op.drop_table('workspace_changes')
    # ### end Alembic commands ###